Email
std::string Email::identifiant
L'identifiant de l'adresse.
std::string Email::domaine
Le domaine de l'adresse.
std::string Email::mc
Le mc de l'adresse.
Email::Email()
Constructeur par défaut de la classe Email.
Ce constructeur initialise une adresse mail vide.
Email::Email(const std::string &)
Constructeur avec paramètre de la classe Email.
string Email::getIdentifiant() const
Pour récuperer la partie identifiant de l'adresse.
Cette fonction renvoie la partie qui se trouve avant le '@' dans l'adresse mail.
Referenced by main.
string Email::getDomaine() const
Pour récuperer la partie domaine de l'adresse.
Cette fonction renvoie la partie qui se trouve entre le '@' et le dernier '.' dans l'adresse mail.
Referenced by main.
string Email::getMc() const
Pour récuperer la partie mc de l'adresse.
Cette fonction renvoie la partie qui se trouve après le dernier '.' dans l'adresse mail.
Referenced by main.
void Email::setDomaine(const std::string &)
Pour definir la partie domaine de l'adresse.
domaine : le domaine de l'adresse
void Email::setIdentifiant(const std::string &)
Pour definir la partie Identifiant de l'adresse.
id : l'identifiant de l'adresse
void Email::setMc(const std::string &)
Pour definir la partie mc de l'adresse.
mc : le mc de l'adresse
void Email::fromString(const std::string &)
Pour décomposer une adresse mail et récupérer les différentes parties.
Cette fonction recupère une adresse mail complète (string) et récupére les différentes parties. Si l'adresse mail a une syntaxe incorrecte, aucune partie n'est enregistrée. adr : de type String, elle représente l'adresse mail complète;
Referenced by main.
string Email::toString()
Referenced by main.