Interaction
tm* Interaction::date
La date de l'intéraction.
Referenced by getDate, Interaction, setDate.
std::string Interaction::contenu
Détails de l'intéraction.
Referenced by getContenu, Interaction, setContenu.
Interaction::Interaction()
Constructeur par défaut de la classe Interaction.
Constructeur par défaut. Ce constructeur initialise une interaction avec un contenu vide et horodaté avec la date courante.
References contenu, date, setDate.
Interaction::Interaction(const std::string &)
Constructeur avec paramètres date et contenu de la classe Interaction.
Constructeur avec paramètre. Ce constructeur initialise une interaction avec un contenu et la date courante. c : le contenu de l'interaction
References contenu, date, setContenu, setDate.
Interaction::~Interaction()
Destructeur de la classe Interaction.
tm Interaction::getDate() const
Accéder à la date.
Pour récupérer la date. Cette fonction renvoie l'instance pointée par date.
References date.
Referenced by GestionInteraction::addInteraction, operator=.
std::string Interaction::getContenu() const
Accéder au contenu.
Pour recupérer le contenu de l'interaction. Cette fonction renvoie la chaine contenu de l'interaction.
References contenu.
Referenced by operator=, operator==.
void Interaction::setDate(const tm &)
Pour affecter une date à l'interaction.
t : structure tm représentant la date à affecter. La structure tm t passée en paramètre est copié dans l'instance pointée par date.
References date.
Referenced by Interaction, operator=, testContact, testGestionContact, testGestionInteraction, testGestionTodo.
void Interaction::setContenu(const std::string &)
Pour affecter un contenu à l'interaction.
c : string à affecter au contenu.
References contenu.
Referenced by Interaction, operator=, testContact, testGestionContact.
bool Interaction::operator==(const Interaction &)
Surchage de l'opérateur de comparaison (==)
On considère que deux intéractions sont identiques si elles ont même contenu. autre : l'intéraction à comparer avec l'intéraction courante. un booléen : true si elles ont le même contenu, false sinon.
References getContenu.
void Interaction::operator=(const Interaction &)
Surchage de l'opérateur d'affection (=)
L'intéraction actuelle reçoit le contenu et la date de l'autre intéraction. autre : l'intéraction à affecter.
References getContenu, getDate, setContenu, setDate.
std::ostream& operator<<(std::ostream &, const Interaction &)
Surcharge de l'opérateur << pour l'affichage.
os : de type ostream. i de type Interaction qui represente l'interface à afficher. Pour afficher une Interaction, on affiche la date de l'interaction, ou Aujourd'hui s'il s'agit de la date courante, suivie son contenu.