Contact
std::string Contact::nom
Le nom du contact.
Referenced by Contact, getNom, setNom.
std::string Contact::prenom
Le prénom du contact.
Referenced by Contact, getPrenom, setPrenom.
std::string Contact::entreprise
Le nom de l'entreprise.
Referenced by Contact, getEntreprise, setEntreprise.
std::string Contact::telephone
Le numéro du contact.
Referenced by Contact, getTelephone, setTelephone.
std::string Contact::URIphoto
La photo du contact.
Referenced by Contact, getPhoto, setPhoto.
tm* Contact::dateCreation
La date de création du contact.
Referenced by Contact, getDateCreation, setDateCreation.
tm* Contact::dateLastModif
La date de dernière modification.
Referenced by Contact, getDateLastModif, setDateLastModif.
Email* Contact::mail
Adresse Mail du contact.
Referenced by Contact, getEmail, setEmail.
GestionInteraction* Contact::listInteractions
Le gestionnaire des intéractions du contact.
Referenced by addInteraction, Contact, getListInteractions, removeInteraction.
void Contact::modification()
Mise à jour de la date de modification.
Mise à jour de la date de dernière mise à jour. Cette méthode permet notamment d'actualiser la date de mise à jour du contact lorsque l'un de ses attributs subi une modification. Elle devient la date courante.
References Date::getDate, setDateLastModif.
Referenced by addInteraction, setEmail, setEntreprise, setNom, setPhoto, setPrenom, setTelephone.
Contact::Contact()
Constructeur par défaut de la classe Contact.
Ce constructeur initialise un contact avec des attributs et un gestionnaire d'intéractions vides. Les dates de création et de modification sont initialisées à la date courante.
References dateCreation, dateLastModif, entreprise, listInteractions, mail, nom, prenom, setDateCreation, setDateLastModif, telephone, URIphoto.
Contact::Contact(const std::string &, const std::string &, const std::string &)
Constructeur avec paramètre nom, prénom, entreprise.
Constructeur de la classe Contact. Ce constructeur initialise un contact avec les attributs nom, prénom et entreprise. Les dates de création et de modification sont initialisées à la date courante, le gestionnaire d'intéraction est vide. name : le nom du contact lastname : le prénom du contact entr : le nom de l'entreprise du contact
References dateCreation, dateLastModif, entreprise, listInteractions, mail, nom, prenom, setDateCreation, setDateLastModif, telephone, URIphoto.
Contact::~Contact()
Destructeur de la classe Contact.
Rien de particulier, les espaces alloués sont effacés en même tant que le gestionnaire de contact. On obtient une erreur de segmentation (Segmentation fault) si on essaie de libérer l'espace alloué par le gestionnaire d'intéraction et une erreur de libération double (double free()) pour celui des dates.
std::string Contact::getNom() const
Pour récuperer le nom du contact.
Cette fonction renvoie le nom du contact. Le nom du contact en String
References nom.
std::string Contact::getPrenom() const
Pour récuperer le prenom du contact.
Cette fonction renvoie le prenom du contact. Le prenom du contact en String
References prenom.
std::string Contact::getEntreprise() const
Pour récuperer le nom de l'entreprise.
Cette fonction renvoie le nom de l'entreprise. Le nom de l'entreprise en String
References entreprise.
std::string Contact::getTelephone() const
Pour récuperer la photo.
Cette fonction ne renvoie pas réellement une photo mais le chemin pour y accéder. Le numéro du contact en String
References telephone.
std::string Contact::getPhoto() const
Pour récuperer la photo ou le chemin vers la photo.
Le lien vers kla photo du contact en String
References URIphoto.
tm Contact::getDateCreation() const
Pour récuperer la date de création du contact.
Une tm contenant la date de création du contact
References dateCreation.
tm Contact::getDateLastModif() const
Pour récuperer la date de dernière modification du contact.
Une tm contenant la date de dernière modification du contact
References dateLastModif.
Email Contact::getEmail() const
Pour récupérer l'adresse mail du contact.
Une variable Email contenant l'adresse mail du contact.
References mail.
GestionInteraction * Contact::getListInteractions() const
Pour récuperer la liste des intéractions.
Cette fonction renvoie le pointeur vers le gestionnaire d'interaction. Un pointeur sur le gestionnaire d'intéraction.
References listInteractions.
void Contact::setNom(const std::string &)
Pour modifier le nom du contact.
Cette fonction permet de modifier le nom du contact. Cette opération entraine une mise à jour de la date de modification. name : Le nouveau nom du contact.
References modification, nom.
void Contact::setPrenom(const std::string &)
Pour modifier le prenom du contact.
Cette fonction permet de modifier le prenom du contact. Cette opération entraine une mise à jour de la date de modification. lastname : Le nouveau prénom du contact.
References modification, prenom.
void Contact::setEntreprise(const std::string &)
Pour modifier le nom de l'entreprise.
Cette fonction permet de modifier le nom de l'entreprise. Cette opération entraine une mise à jour de la date de modification. company : Le nouveau nom de l'entreprise.
References entreprise, modification.
void Contact::setTelephone(const std::string &)
Pour modifier le numéro du contact.
Cette fonction permet de modifier le numéro du contact. Cette opération entraine une mise à jour de la date de modification. phone : Le nouveau numéro du contact.
References modification, telephone.
Referenced by testContact, testGestionContact.
void Contact::setPhoto(const std::string &)
Pour modifier la photo.
Cette opération entraine une mise à jour de la date de modification. le lien vers la nouvelle photo.
References modification, URIphoto.
Referenced by testGestionContact.
void Contact::setDateCreation(const tm &)
Pour modifier la date de création du contact.
date_of_creation : la date de création du contact.
References dateCreation.
Referenced by Contact, testContact, testGestionContact.
void Contact::setDateLastModif(const tm &)
Pour modifier la date de dernière modification.
References dateLastModif.
Referenced by Contact, modification, testContact, testGestionContact.
void Contact::setEmail(const std::string &)
Pour modifier l'adresse mail du contact.
Cette opération entraine une mise à jour de la date de modification. email : l'adresse mail sous forme de String. Si l'adresse est incorrecte un message d'erreur s'affiche.
References Email::fromString, mail, modification.
Referenced by testContact, testGestionContact.
void Contact::addInteraction(const Interaction &)
Ajouter une interaction.
Ajouter une intéraction au contact. Cette fonction permet d'ajouter une intéraction dans le gestionnaire. Cette opération entraine une mise à jour de la date de modification. add_interact : l'intéraction à ajouter.
References GestionInteraction::addInteraction, listInteractions, modification.
Referenced by testContact, testGestionContact.
void Contact::removeInteraction(const std::string &)
Supprimer une interaction.
Supprimer une intéraction au contact. Cette fonction permet de supprimer une intéraction du gestionnaire en connaissant son contenu. contenu_interact : le contenu (String) de l'intéraction à supprimer.
References listInteractions, GestionInteraction::removeInteraction.
std::ostream& operator<<(std::ostream &, const Contact &)
Surcharge de l'opérateur << pour l'affichage.
os : de type ostream. c de type contact qui represente le contact à afficher. Pour afficher la fiche d'un contact. os