Date
tm* Date::d
Date::Date()
Constructeur par défaut de la classe Date.
Constructueur par défaut. Avec le constructeur par défaut, la date est initialisé à la date courante
Date::Date(const int, const int, const int)
Constructeur avec paramètre jour, mois et année de la classe Date.
Constructeur avec paramètre. Avec ce constructeur, on indique le jour, le mois et l'année souhaité day : le jour; month : le mois; year : l'année;
int Date::getJour()
Récuperer le jour.
Récupération du jour de la date. un entier qui représente le jour
int Date::getMois()
Récuperer le mois.
Récupération du mois de la date. un entier qui représente le mois
int Date::getAnnee()
Récuperer l'annee.
Récupération de l'année de la date. un entier qui représente l'année
tm Date::getDate()
Récupération de la date.
Cette fonction renvoie l'instance tm pointée par d. une tm contenant la date;
Referenced by Contact::modification, testContact, testDateComparator, testGestionContact, testGestionInteraction, testGestionTodo.
void Date::setDate(const tm &)
Referenced by GestionInteraction::addInteraction, testDateComparator.
void Date::fromDate(const int day, const int month, const int year)
Récupération en fonction des paramètres day, month et year d'une structure tm contenant la date définie.
day : le jour de la nouvelle date month : le mois de la nouvelle date year : l'année de la nouvelle date
Referenced by testContact, testDateComparator, testGestionContact, testGestionInteraction, testGestionTodo.
string Date::toString()
Récupération de la date avec le format jj/mm/aaaa.
Chaine de caractère contenant la date
bool Date::operator==(const tm &)
Surchage de l'opérateur d'égalité
Cette fonction compare deux dates. Elle renvoie true si les jours, mois et années sont identiques. autre : le tm à comparer avec le tm de la date actuelle. un booléen : true si les deux dates ont même jour, même mois et même année et false sinon.
bool Date::operator<(const tm &)
Surcharge de l'opérateur de comparaison inférieur.
Cette fonction compare deux dates. Elle renvoie true si la date actuelle est antérieure à l'autre date. autre : le tm à comparer avec le tm de la date actuelle. un booléen : true si la date actuelle est antérieure à autre.
bool Date::operator>(const tm &)
Surcharge de l'opérateur de comparaison supérieur.
Cette fonction compare deux dates. Elle renvoie true si la date actuelle est supérieure à l'autre date. autre : le tm à comparer avec le tm de la date actuelle. un booléen : true si la date actuelle est supérieure à autre.
bool Date::operator<=(const tm &)
Surcharge de l'opérateur de comparaison inférieur ou égale.
Cette fonction compare deux dates. Elle renvoie true si la date actuelle est inférieure ou égale à l'autre date. autre : le tm à comparer avec le tm de la date actuelle. un booléen : true si la date actuelle est inférieure ou égale à autre.
bool Date::operator>=(const tm &)
Surcharge de l'opérateur de comparaison supérieur ou égale.
Cette fonction compare deux dates. Elle renvoie true si la date actuelle est supérieure ou égale à l'autre date. autre : le tm à comparer avec le tm de la date actuelle. un booléen : true si la date actuelle est supérieure ou égale à autre.