GestionInteraction
std::list<Interaction> GestionInteraction::listInteraction
La liste des intéractions.
Referenced by addInteraction, addTodo, getListInteraction, removeInteraction, removeTodo, SetlistInteraction, ~GestionInteraction.
GestionTodo* GestionInteraction::listTodo
Le gestionnaire de taches.
Referenced by addTodo, GestionInteraction, getListTodo, removeInteraction, removeTodo, ~GestionInteraction.
GestionInteraction::GestionInteraction()
Constructeur par défaut du gestionnaire d'intéraction.
Construteur par défaut de la classe GestionInteraction. Ce constructeur initialise un gestion de tâches vide.
References listTodo.
GestionInteraction::~GestionInteraction()
Destructeur du gestionnaire d'intéraction.
Destructeur de la classe GestionInteraction. Libération de la mémoire allouée à la liste d'intéraction et au gestionnaire de tâches.
References listInteraction, listTodo.
std::list<Interaction> GestionInteraction::getListInteraction() const
References listInteraction.
void GestionInteraction::SetlistInteraction(std::list< Interaction > val)
References listInteraction.
GestionTodo* GestionInteraction::getListTodo() const
References listTodo.
void GestionInteraction::addInteraction(const Interaction &)
Ajouter une interaction.
Ajouter une interaction à la liste des intéractions. Avant d'inserer l'intéraction dans la liste, on la parcourt pour trouver une intéraction avec une date supérieure. L'intéraction est placée dans la liste juste avant celle-ci, si aucune date supérieure n'a été trouvé, elle est placé en fin de liste. De cette façon, on a toujours une liste d'intéraction triée par ordre croissant des dates.
References Interaction::getDate, listInteraction, Date::setDate.
Referenced by Contact::addInteraction, testGestionInteraction.
void GestionInteraction::removeInteraction(const std::string &)
Supprimer une intéraction.
Supprimer une intéraction de la liste. Cette fonction permet de supprimer une intéraction correspondant au contenu donné. La suppression d'une intéraction conduit à la suppression de toutes ses tâches dans le gestionnaire de tâches. contenu : le contenu correspondant à la fonction à supprimer.
References GestionTodo::getAllInteractionTodo, GestionTodo::getlistTodo, listInteraction, listTodo, removeTodo.
Referenced by Contact::removeInteraction, testGestionInteraction.
void GestionInteraction::addTodo(const std::string &, Todo &)
Ajouter une tache.
Pour ajouter une tâche à une intéraction. Cette fonction permet d'ajouter une tâche et de la relier à une intération donnée. Si l'intéraction en question n'existe pas ou n'existe plus, la tâche n'est pas ajoutée et un message d'erreur s'affiche. interact_contenu : le contenu de l'intéraction à qui ajouter la tâche; td : la tâche à ajouter;
References GestionTodo::addTodo, listInteraction, listTodo, Todo::setInteraction.
Referenced by testGestionInteraction.
void GestionInteraction::removeTodo(const std::string &, const std::string &)
Supprimer une tache.
Pour supprimer une tâche d'une intéraction. Cette fonction supprime une tâche en lui indiquant son contenu et le contenu de l'intéraction à laquelle elle appartient. interact_contenu : le contenu de l'intéraction; todo_contenu : le contenu de la tâche;
References listInteraction, listTodo, GestionTodo::removeTodo.
Referenced by removeInteraction.
std::ostream& operator<<(std::ostream &, const GestionInteraction &)
Surcharge de l'opérateur << pour l'affichage.
os : de type ostream. gest de type GestionInteraction qui represente le gestionnaire à afficher. Afficher un gestionnaire d'intéraction revient à afficher toutes les intéractions chacune suivie de l'affichage de toutes ses tâches. os