GestionTodo
std::list<Todo> GestionTodo::listTodo
La liste des tâches.
Referenced by addTodo, getAllInteractionTodo, getlistTodo, getSize, removeAllInteractionTodo, removeTodo, ~GestionTodo.
GestionTodo::GestionTodo()
Constructeur par défaut.
Constructeur par défaut de la classe GestionTodo. Rien de particulier dans ce constructeur.
GestionTodo::~GestionTodo()
Destructeur.
Destructeur de la classe GestionTodo. Libération de la mémoire alloué à la liste de tâches.
References listTodo.
const std::list<Todo> GestionTodo::getlistTodo() const
Accesseur sur la liste de tâches.
Cette methode renvoie la liste des tâches. une liste de tâches.
References listTodo.
Referenced by GestionInteraction::removeInteraction.
unsigned GestionTodo::getSize()
Récupération de la taille de la liste.
References listTodo.
void GestionTodo::addTodo(const Todo &)
Pour ajouter une tâche à la liste.
Cette fonction permet d'ajouter une tâche à la liste. todo : la tâche (todo) à ajouter.
References listTodo.
Referenced by GestionInteraction::addTodo, getAllInteractionTodo, testGestionTodo.
void GestionTodo::removeTodo(const std::string &)
Pour supprimer une tâche de la liste.
Cette méthode permet supprimer une tâche en fonction de son contenu. contenu : le contenu de la tâche à supprimer.
References listTodo.
Referenced by GestionInteraction::removeTodo, testGestionTodo.
void GestionTodo::removeAllInteractionTodo(const Interaction &)
Pour supprimer toutes les tâches liées à une intéraction donné.
Cette méthode parcourt toute la liste des tâches et supprime toutes celles qui correspondent à l'intéraction. interact : l'intéraction dont les tâches sont à supprimer.
References listTodo.
Referenced by testGestionTodo.
GestionTodo GestionTodo::getAllInteractionTodo(const Interaction &) const
Pour récuperer toutes les tâches d'une intéraction.
Cette fonction récupère une intéraction et renvoie un gestionnaire de tâches ne contenant que celles qui lui sont liées. interact : l'intéraction dont on retournera les tâches; un gestionnaire de tâches appartenant toutes à une même intéraction.
References addTodo, listTodo.
Referenced by GestionInteraction::removeInteraction, testGestionTodo.
std::ostream& operator<<(std::ostream &, const GestionTodo &)
Surcharge de l'opérateur << pour l'affichage.
os : de type ostream. gest de type GestionTodo qui represente le gestionnaire à afficher. Afficher un gestionnaire de tâches revient à afficher toutes les tâches qu'elle contient. os