Todo
Interaction* Todo::lienInteraction
std::string Todo::contenu
Lien vers l'interaction.
struct tm* Todo::date
Le contenu.
Todo::Todo()
La date.
Constructeur par défaut de la classe Todo. Ce constructeur initialise à la date courante un Todo avec un contenu vide n'étant relié à aucune interaction;
Todo::Todo(const Interaction &, const std::string &, const tm &)
Constructeur avec paramètres de la classe Todo.
Ce constructeur initialise à une date donnée un Todo avec un contenu vide n'étainteraction;
Interaction Todo::getInteraction() const
Accesseurs.
Pour récuperer l'intéraction à laquelle apppartient le Todo. Ce fontion renvoie l'instance Intéraction à laquelle appartient le Todo.
std::string Todo::getContenu() const
Pour recupérer le contenu de l'interaction.
Cette fonction renvoie la chaine contenu de l'interaction.
tm Todo::getDate() const
Pour récupérer la date.
Cette fonction renvoie l'instance pointée par date.
void Todo::setInteraction(const Interaction &)
Mutateurs.
Pour lier une intéraction à la classe Todo. inter : l'intéraction à lier au Todo.
Referenced by Todo.
void Todo::setContenu(const std::string &)
Pour affecter un contenu à l'interaction.
c : string à affecter au contenu.
Referenced by main, Todo.
void Todo::setDate(const tm &)
Pour affecter une date à l'interaction.
t : structure tm représentant la date à affecter. La structure tm t passée en paramètre est copié dans l'instance pointée par date.
Referenced by Todo.
std::ostream& operator<<(std::ostream &, const Todo &)
Surcharge de l'opérateur << pour l'affichage.
os : de type ostream. td de type Todo qui represente le Todo à afficher. Pour afficher un Todo, on affiche son contenu suivie de sa date.