#!/bin/bash

FichNom= $1
FichPDF= $2


while read NOM PRENOM
do
    DIR = `echo $NOM $PRENOM` | tr -d ' ' | tr [:lower][:upper]
    mkdir $DIR
    cp $FichPDF $DIR
    ListDir= $DIR $ListDIR

done < $FichNom